version: "3"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pa
      - POSTGRES_DB=task
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=pa
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: